accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView

app_name='accountapp'

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    ]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleListView, ArticleDeleteView

app_name='articleapp'

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    ]

homeboardapp/urls.py
from django.urls import path

from homeboardapp.views import family_sns, homeboard, start_work

app_name='homeboardapp'

urlpatterns = [
    path('start_work/', start_work, name='home'),
    path('family_sns/', family_sns, name='family_sns'),
    path('homeboard', homeboard, name='homeboard'),
    ]

sweethome4/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import homeboardapp
from homeboardapp.views import start_work

urlpatterns = [
    path('', start_work,name='home'),
    path('admin/', admin.site.urls),
    path('homeboard/', include('homeboardapp.urls')),
    path('account/', include('accountapp.urls')),
    path('article/', include('articleapp.urls')),
    path('familyjoin/', include('familyjoinapp.urls')),
    path('accounts/login/', LoginView.as_view(template_name='homeboardapp/start_work.html'), name='start_work'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family='NanumSquareR'">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>



</body>
</html>

templates/head.html
<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HomeBoard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>

templates/header.html
 <header>

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a href="{% url 'homeboardapp:homeboard' %}" class="nav-link">홈보드가기</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'articleapp:create' %}" class="nav-link">글쓰기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'articleapp:list' %}">내가 쓴 글</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'accountapp:logout' %}?next={% url 'home' %}" class="nav-link">로그아웃</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>