accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView

app_name='accountapp'

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    ]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleListView, ArticleDeleteView

app_name='articleapp'

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ArticleUpdateView.as_view(), name='update'),
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    ]

sweethome4/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import homeboardapp
from homeboardapp.views import start_work

urlpatterns = [
    path('', start_work,name='home'),
    path('admin/', admin.site.urls),
    path('homeboard/', include('homeboardapp.urls')),
    path('account/', include('accountapp.urls')),
    path('article/', include('articleapp.urls')),
    path('familyjoin/', include('familyjoinapp.urls')),
    path('accounts/login/', LoginView.as_view(template_name='homeboardapp/start_work.html'), name='start_work'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='old_article', null=True)
    # family = models.ForeignKey(Family, on_delete=models.SET_NULL, related_name='articles', null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(max_length=500, null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

class NewArticle(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article_written')
    # family = models.ForeignKey(Family, on_delete=models.SET_NULL, related_name='articles', null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(max_length=500, null=True)
    created_at = models.DateField(null=True)
    # 나머지 모델 필드들

articleapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from articleapp.models import Article, NewArticle


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields=[ 'image', 'content']

class NewArticleCreationForm(ModelForm):
    class Meta:
        model = NewArticle
        fields = ['image', 'content', 'created_at']
        widgets = {
            'created_at': forms.SelectDateWidget()
        }

    def __init__(self, user, *args, **kwargs):
        super(NewArticleCreationForm, self).__init__(*args, **kwargs)

        # 기존 필드 제거
        self.fields.pop('writer', None)

        self.fields['writer'] = forms.ModelChoiceField(queryset=User.objects.filter(pk=user.pk), initial=user.pk,
                                                       widget=forms.HiddenInput())

    def save(self, commit=True):
        # 저장 시 writer와 group 정보 추가
        instance = super(NewArticleCreationForm, self).save(commit=False)
        instance.writer = self.cleaned_data['writer']

        if commit:
            instance.save()

        return instance

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import FormMixin, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from articleapp.forms import ArticleCreationForm, NewArticleCreationForm
from articleapp.models import NewArticle

has_ownership=[
            login_required,
            account_ownership_required
]
# Create your views here.

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = NewArticle
    form_class = NewArticleCreationForm
    template_name = 'articleapp/create.html'
    success_url = reverse_lazy('homeboardapp:homeboard')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # 로그인한 사용자 정보
        return kwargs



class ArticleDetailView(LoginRequiredMixin, DetailView, FormMixin):
    model = NewArticle
    form_class = NewArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'
    success_url = reverse_lazy('homeboardapp:homeboard')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # 로그인한 사용자 정보
        return kwargs


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = NewArticle
    form_class = NewArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'
    success_url = reverse_lazy('homeboardapp:homeboard')
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # 로그인한 사용자 정보
        return kwargs



class ArticleListView(LoginRequiredMixin, ListView):
    model = NewArticle
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        article_list = NewArticle.objects.filter(writer=user).order_by('-created_at')
        return article_list



class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = NewArticle
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'
    success_url = reverse_lazy('articleapp:list')

    def get_object(self, queryset=None):
        obj = super().get_object()
        return obj

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 30%; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Create</h4>
    </div>
    <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary rounded-pill col-3 mt-3">

    </form>
  </div>


{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 30%; margin: 4rem auto">
    <div class="mb-4">
      <h4>Delete Update</h4>
    </div>
    <form action="{% url 'articleapp:delete' target_article.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary rounded-pill col-3 mt-3">

    </form>
  </div>


{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="container">
        <h4 class="text-center mt-auto">Article Update</h4>
    </div>

    <div>

            <div style="text-align: center; max-width: 700px; margin:1rem auto">
                <h1>
                    {{ target_article.title }}
                </h1>

                <hr>

                <img src="{{ target_article.image.url }}" alt="" style="width: 50%; border-radius: 1rem; margin: 2rem 0">

                <p>
                    {{ target_article.content }}
                </p>
            </div>
    </div>
    <hr>
    <div class="d-flex justify-content-center g-3">
        <div class="p-1 m-1">
            <a href="{% url 'articleapp:update' pk=target_article.pk %}"  style="text-decoration: none;"> <h5 class="text-center mt-3 text-primary">수정하기</h5></a>
        </div>
        <div class="p-1 m-1">
             <a href="{% url 'articleapp:delete' pk=target_article.pk %}" style="text-decoration: none;"><h5 class="text-center mt-3 text-danger">삭제하기</h5></a>
        </div>

    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    {% if article_list %}
        {% for article in article_list %}
            <div class="container justify-content-center align-content-around row-gap-3 column-gap-3">
                <div class="row align-items-center h-25 shadow-lg p-4">
                    <div class="col-12 col-lg-4 overflow-auto">
                        <div class="container justify-content-center">
                            <div class="row align-items-center" style="float: none; margin: auto;">
                                <div class="col-6">
                                    <img src="{{ article.image.url }}" class="img-fluid" alt="Article Image" style="width: 200px; height: 200px; object-fit: cover;">
                                </div>
                                <div class="col-6" style="height: 100px; display: flex; flex-direction: column; justify-content: space-between; align-items: flex-end;">
                                    <div style="color: black; text-decoration: none; margin: 8px 0;">
                                        <h4 style="margin: 0;">{{ article.created_at }}</h4>
                                    </div>
                                    <div style="color: black; text-decoration: none; margin: 8px 0;">
                                        <a href="{% url 'articleapp:detail' pk=article.pk %}" style="text-decoration: none; color: black;">자세히보기</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-8 lh-lg overflow-hidden align-center">
                        <p>{{ article.content|slice:":200" }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="pagination" style="display: flex; justify-content: center; margin-top: 20px; font-size: 1.2em;">
            <span class="step-links" style="display: flex;">
                {% if article_list.has_previous %}
                    <a href="?page=1" style="text-decoration: none; color: black; margin-right: 1ex;">&laquo; first</a>
                    <a href="?page={{ article_list.previous_page_number }}" style="text-decoration: none; color: black; margin-right: 1ex;">previous</a>
                {% endif %}

                <span class="current" style="margin: 0 10px; text-decoration: none; color: black;">
                    Page {{ article_list.number }} of {{ article_list.paginator.num_pages }}.
                </span>

                {% if article_list.has_next %}
                    <a href="?page={{ article_list.next_page_number }}" style="text-decoration: none; color: black; margin-left: 1ex;">next</a>
                    <a href="?page={{ article_list.paginator.num_pages }}" style="text-decoration: none; color: black; margin-left: 1ex;">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh;">
            <h1>새로운 게시글을 써보세요!</h1>
        </div>
    {% endif %}
{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 30%; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Update</h4>
    </div>
    <form action="{% url 'articleapp:update' target_article.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary rounded-pill col-3 mt-3">

    </form>
  </div>


{% endblock %}